### ISSUE TITLE
[TRACKING] Missing API Endpoints

### ISSUE THREAD

**Issue by sQu4rks** [CiscoDevNet/webexteamssdk#113]
In accordance to the [Release Plan](https://github.com/CiscoDevNet/webexteamssdk/wiki/Release-Plans) this is a issue to track all API endpoints that are present on developer.webex.com but not yet implemented in the v1.x of the SDK: 

### Webex Devices
- [ ] Devices (`/v1/devices`)
- [ ] Device Activation Code (`/v1/devices/activationCode`)
- [ ] Places (`/v1/places`)
- [ ] xapi (`/v1/xapi`) 

### Webex Meetings
- [ ] Meeting Invitees (`/v1/meetingInvitees`) 
- [ ] Meeting Preferences (`/v1/meetingPreferences`)
- [ ] Meetings (`/v1/meetings`)
- [ ] Recordings (`/v1/recordings`) 

### Misc
- [ ] Admin Audit Events (`/v1/adminAudit/events`) 
- [ ] Hybrid Clusters (`/v1/hybrid/clusters` ) 
- [ ] Hybrid Connectors (`/v1/hybrid/connectors`)
- [ ] Resource Group Membership (`/v1/resourceGroup/memberships`) 
- [ ] Resource Group (`/v1/resourceGroups`)

**Comment by cmlccie** [comment]
Added support for the *Admin Audit Events* API in **v1.4**.

**Comment by cmlccie** [comment]
@sQu4rks, I am starting work on the **Webex Meetings Endpoints** listed above.

**Comment by cmlccie** [comment]
After discussing the expansion of the developer.webex.com APIs (beyond just Webex Teams APIs), the cumbersomeness under the existing codebase to add (test and document) new API wrappers, and how some more modern tooling and design principles could make these efforts much more sustainable...

We have decided to update the existing Webex Teams API endpoints (adding new parameters, missing attributes, and new sub-endpoints) and then to put the v1.x release in maintenance mode.  We will add Webex API completeness to the goals for the 2.x version, which we will retool and refactor to improve both the community and client user experience in working with the library.

**Comment by sumitmcc** [comment]
@sQu4rks I am working on the Recordings (/v1/recordings).

**Comment by sumitmcc** [comment]
Submitted a PR for Recordings API
